version: "3.8"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LOCALSTACK_AUTH_TOKEN=test
      - LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT=1
      - DEBUG=0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "localstack-data:/var/lib/localstack"

volumes:
  localstack-data:
