name: CI (llamando reusable)

on:
  push:
    branches: [ "main" ]

jobs:
  python-ci:
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    uses: margasor/NivelMedio/.github/workflows/reusable-python-ci.yml@main
    with:
      python-version: ${{ matrix.python-version }}
      src-path: "src"
      tests-path: "tests"
